{"name": "test_login_incorrecto", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Locator.wait_for: Timeout 30000ms exceeded.\nCall log:\n  - waiting for locator(\"input[type=\\\"passwordd\\\"]\") to be visible", "trace": "page = <Page url='http://localhost:3000/login'>\n\n    def test_login_incorrecto(page):\n        \"\"\"Test para verificar que el login falla con credenciales incorrectas\"\"\"\n    \n        # Crear instancia de la página de login\n        login_page = LoginPage(page)\n        # Ir a la página de login\n        login_page.ir_a_login()\n        # Llenar el email y la contraseña incorrectos\n        email_incorrecto = os.getenv('EMAIL_INCORRECTO')\n        password_incorrecto = os.getenv('PASSWORD_INCORRECTO')\n        login_page.llenar_email(email_incorrecto)\n>       login_page.llenar_password(password_incorrecto)\n\nTests/test_login.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nPages/LoginPage.py:44: in llenar_password\n    self.funcion.llenar_texto(self.input_password, password)\nFunciones.py:12: in llenar_texto\n    campo.wait_for(state=\"visible\")\n.venv/lib/python3.13/site-packages/playwright/sync_api/_generated.py:17956: in wait_for\n    self._sync(self._impl_obj.wait_for(timeout=timeout, state=state))\n.venv/lib/python3.13/site-packages/playwright/_impl/_locator.py:692: in wait_for\n    await self._frame.wait_for_selector(\n.venv/lib/python3.13/site-packages/playwright/_impl/_frame.py:369: in wait_for_selector\n    await self._channel.send(\n.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:69: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x106212660>\ncb = <function Channel.send.<locals>.<lambda> at 0x1065d9940>\nis_internal = False, title = None\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False, title: str = None\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(\n            task, \"__pw_stack__\", None\n        ) or inspect.stack(0)\n    \n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal, title)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Locator.wait_for: Timeout 30000ms exceeded.\nE           Call log:\nE             - waiting for locator(\"input[type=\\\"passwordd\\\"]\") to be visible\n\n.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:558: TimeoutError"}, "description": "Test para verificar que el login falla con credenciales incorrectas", "start": 1753722550461, "stop": 1753722581274, "uuid": "7ae5b213-af2b-40e2-a009-a363cfbeec56", "historyId": "1a7c0073c4b528c4a9aa616ca651f6c7", "testCaseId": "1a7c0073c4b528c4a9aa616ca651f6c7", "fullName": "Tests.test_login#test_login_incorrecto", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MacBook-Pro-de-emiliano.local"}, {"name": "thread", "value": "58168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}], "titlePath": ["Tests", "test_login.py"]}